services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - backend

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    networks:
      - backend

  api:
    image: api8:latest
    ports:
      - "8088:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ContosoUniversity;User Id=SA;Password=${SA_PASSWORD};TrustServerCertificate=True
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    depends_on:
      - sqlserver
      - seq
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  sqlserver_data:
  seq_data: